[package]
name = "gmail-notes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
lettre = "0.10.4"
mailparse = "0.14.0"
native-tls = "0.2.11"
